# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_name', models.CharField(help_text='Name of the genres', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(help_text='Name of the Track', max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('genres', models.ForeignKey(help_text='Genres the title belongs to', on_delete=django.db.models.deletion.CASCADE, to='mtracks.Genres')),
            ],
        ),
    ]
