# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import mtracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('mtracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genres_name',
            field=models.CharField(help_text='Name of the genres', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='rating',
            field=models.IntegerField(default=0, validators=[mtracks.models.validate_ratings]),
        ),
    ]
